### ISSUE TITLE
Review Process in Web App same as in Mobile App

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/stoplight-web#148]
Write down how the process of getting an issue and reviewing it works in the web app.

**Comment by pA1nD** [comment]
### Problem 

The Web App does not follow best practices regarding Git Workflow. This leads to a bad developer performance and bugs.

### Solution

Use the same GIT Workflow as we use in the mobile app.

The workflow is called `GIT Feature Branch Workflow` and is described here:
https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

In it's core, it follows the following steps:

(1) Select one issue on Github that you will work on next (if there is no issue for the work, create one)
(2) Create a new branch from master. Name: issue-<nr>/<description>
(3) Develop the feature in this branch
(4) Create a PR from this branch to master once ready
(5) A peer merges the PR after a code review has been conducted.

**Comment by gigerbytes** [comment]
Current Process:

1.  Dev takes an issue and creates a new branche <username>-<issue#>-<description>
2. Works on it and puts it to review
3. If reviewed, its merged to develop branch (because breaking changes will affect master that is depolyed to production>)
4. If no breaking changes, the dev branch is merged to master
