### ISSUE TITLE
Back Button in LifeMap Online - Ends at indicators

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#349]
When I go to the review screen of the life map (thus I have completed all fields) but then go back through the survey, screen by screen by screen.....
The back button only allows me to go to the first indicator - Thus I have no option to go back further than this and cannot enter the socio economic pages again

**Comment by javierpf** [comment]
@stacylorraineprendeville as I mentioned some days ago, browsers limit the number of elements in the browsing history. That's why, after going back 50 times using the browser's back button, you eventually get stuck and cannot go back anymore. 
Maybe we could provide something like a breadcrumb (https://next.material-ui.com/components/breadcrumbs/) navigation option?
Either way, I think we should talk about this during the next grooming session.

**Comment by javierpf** [comment]
@stacylorraineprendeville we would have to agree about a possible solution for this issue. Please note the comment above.

**Comment by stacylorraineprendeville** [comment]
@javierpf I see the comment but I am not sure breadcrumbs is the right approach unless we can go Family > Indicators otherwise would we need end up with a list of over 50 pages in the breadcrumb?
