### ISSUE TITLE
UK cut images in production

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#420]
UK reported that their images are cut in the web version. 
I CANNOT see this in the demo environment. 

![unnamed.png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/b9a69691-efbc-49c2-8577-42f90f851ab9)

![unnamed (1).png](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/e93c2883-3c58-4f43-baad-d127c32f8780)

**Comment by stacylorraineprendeville** [comment]
@javierpf Can you complete the code review today - This is a client who causes a lot of difficulties for our internal team.

**Comment by aprojas** [comment]
How can I test this if it's in production? I don't have users for that environment @javierpf

**Comment by stacylorraineprendeville** [comment]
@javierpf @aprojas I am adding our new HOT FIX tag here becuase of the excessive client complaints

**Comment by stacylorraineprendeville** [comment]
@javierpf provides the link and stephanie will check via Ana

**Comment by aprojas** [comment]
Javier and I figured out what the real problem is!
Their browser had their zoom out more than 90%. That's why it looked like this. It's not a bug or anything. 
This will be fixed in the next release, right @javierpf ?

@stacylorraineprendeville

**Comment by javierpf** [comment]
That's right! It'll appear correctly event if users zoom-out. This is already available for testing in the testing env.

**Comment by stacylorraineprendeville** [comment]
@aprojas jeepers..can you explain this to the UK - Make it clear how much time is lost in our team becuase of this - Its really not OK and also means very clearly that their claims that none of their clients could use the survey because of this is complete nonsense - It was never seen by clients if this was the condition - unless we are assuming all clients were using the magnifier zoom at the exact percentage as UK - highly unlikely.

in future Ana ask the UK to check on a secondary desktop so we can make sure when we are dealing with their very own desktop settings and not a bug.

Incredible!
