### ISSUE TITLE
No logout button available

### ISSUE THREAD

**Issue by aprojas** [FundacionParaguaya/stoplight-web#435]
There isn't a "Log out" button in either demo or testing environments when I log in with demo/demo. 
The user has to click in Households or another tab in order to log out. 

1. I go to testing.povertystoplight.org or demo.povertystoplight.org
2. I log in with demo-demo
3. I take a survey
4. I want to log in as a Hub or Org
5. BUT I cannot log out of this user when I click on the "Demo" button in the upper right hand corner.
6. I can only log out if I click on Households tab or any other tab to return to the previous version of the web. 

![logout button.PNG](https://images.zenhubusercontent.com/5c48c8dbf883486cde30d849/5f3345f2-aefc-489d-b7b7-11ac15b1effd)

**Comment by stacylorraineprendeville** [comment]
@aprojas can you explain the WHERE more effectively......
Review the bug template again :) we can look at it as well in our meeting next week

**Comment by aprojas** [comment]
There :) @stacylorraineprendeville

**Comment by javierpf** [comment]
@aprojas @stacylorraineprendeville we don't have a log out for the stoplight web because we don't have a login functionality for it. 
We use the authorization token that is generated in the PSP platform, which means that if a user logs out from stoplight-web, their PSP session gets invalidated and will be logged out from there as well. 
If this 'shared' behavior is valid for you, we can implement the logout functionality.

**Comment by stacylorraineprendeville** [comment]
@javierpf not sure I understand 100% but if you can implement this - great... ;) Let me know if there is something I do not understand and need to.....
