### ISSUE TITLE
Browser Back Button in Resume Draft

### ISSUE THREAD

**Issue by stacylorraineprendeville** [FundacionParaguaya/stoplight-web#658]
## Problem

When I use the Browser back button in from a draft the back buttons behaviour is not standard
It takes me to the previous page of the survey NOT the previous page I visited.

## Solution

The Browser back button should follow the users path online - not the survey pages

**Comment by javierpf** [comment]
@stacylorraineprendeville the whole navigation through a survey process is based on the browser's history. What we do is to save the whole navigation history in the draft, so that whenever the user resumes a draft, the navigation behaves exactly the way they left it. So, if they want to leave the draft again, they'll have to click the `X` button and confirm that their current changes are going to be saved as a draft.
We should talk about the expected behavior here, since this is working as originally intended.
